services:
  s3:
    url: https://${BUNDLE_SERVICE_BUCKET_NAME}.s3.${AWS_REGION}.amazonaws.com
    credentials:
      s3_signing:
        environment_credentials: {}

bundles:
  authz:
    service: s3
    resource: bundle.tar.gz
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 30