services:
  gcp:
    url: https://storage.googleapis.com/storage/v1/b/${BUNDLE_SERVICE_BUCKET_NAME}/o
    credentials:
      oauth2:
        grant_type: jwt_bearer
        token_url: https://oauth2.googleapis.com/token
        signing_key: jwt_signing_key # references the key in `keys` below
        scopes:
        - https://www.googleapis.com/auth/devstorage.read_only
        additional_claims:
          aud: https://oauth2.googleapis.com/token
          iss: ${BUNDLE_SERVICE_ISS}

bundles:
  authz:
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 30
    service: gcp
    # NOTE ?alt=media is required
    resource: 'bundle.tar.gz?alt=media'

keys:
  jwt_signing_key:
    algorithm: RS256
    private_key: "${BUNDLE_SERVICE_SIGNING_KEY}"

decision_logs:
  console: true
