apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexa-demo
spec:
  selector:
    matchLabels:
      app: hexa-demo
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: hexa-demo
        tier: frontend
    spec:
      containers:
        - name: hexa-demo
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_PROJECT_NAME}/hexa:tag1
          imagePullPolicy: Always
          command:
            - demo
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PORT
              value: "8886"
            - name: OPA_SERVER_URL
              value: http://hexa-demo-opa-server-agent.default.svc.cluster.local:8887/v1/data/authz/allow
            - name: AWS_REGION
              value: "${AWS_REGION}"
            - name: AWS_COGNITO_USER_POOL_DOMAIN
              value: "${AWS_COGNITO_USER_POOL_DOMAIN}"
            - name: AWS_COGNITO_DOMAIN_REDIRECT_URL
              value: "${AWS_COGNITO_DOMAIN_REDIRECT_URL}"
            - name: AWS_COGNITO_USER_POOL_ID
              value: "${AWS_COGNITO_USER_POOL_ID}"
            - name: AWS_COGNITO_USER_POOL_CLIENT_ID
              value: "${AWS_COGNITO_USER_POOL_CLIENT_ID}"
            - name: AWS_COGNITO_USER_POOL_CLIENT_SECRET
              value: "${AWS_COGNITO_USER_POOL_CLIENT_SECRET}"
          ports:
            - containerPort: 8886
