services:
  - name: hexaBundleServer
    url: ${HEXA_CONFIG_URL}
    tls:
      ca_cert: ${HEXA_CA_CERT}

bundles:
  hexaPolicy:
    service: hexaBundleServer
    resource: bundles/bundle.tar.gz
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 30

decision_logs:
  console: true
