apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexa-demo
spec:
  selector:
    matchLabels:
      app: hexa-demo
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: hexa-demo
        tier: frontend
    spec:
      containers:
        - name: hexa-demo
          image: hexaregistry.azurecr.io/hexa:tag1
          imagePullPolicy: Always
          command:
            - demo
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PORT
              value: "8881"
            - name: OPA_SERVER_URL
              value: ${OPA_SERVER_URL}/v1/data/authz/allow

          ports:
            - containerPort: 8881
