#!/usr/bin/env ruby

tap "denisidoro/tools"
tap "buildpacks/tap"

brew "asdf"
brew "bash"
brew "bat"
brew "coreutils"
brew "docpars"
brew "direnv"
brew "overmind"

brew "pack"
brew "golang-migrate"

#cask "docker"
