apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexa-demo-config
spec:
  selector:
    matchLabels:
      app: hexa-demo-config
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: hexa-demo-config
        tier: frontend
    spec:
      containers:
        - name: hexa-demo-config
          image: ${AZ_ACR_NAME}.azurecr.io/hexa:tag1
          imagePullPolicy: Always
          command:
            - democonfig
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PORT
              value: "8889"
          ports:
            - containerPort: 8889
