apiVersion: v1
kind: Service
metadata:
  name: hexa-demo-config
  labels:
    app: hexa-demo-config
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8889
      targetPort: 8889
  selector:
    app: hexa-demo-config
    tier: frontend
