apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hexa-demo-config
  name: hexa-demo-config
  namespace: hexa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexa-demo-config
  template:
    metadata:
      labels:
        app: hexa-demo-config
    spec:
      containers:
        - image: ${IMAGE}
          name: hexa-demo-config
          imagePullPolicy: Always
          command:
            - democonfig
          env:
            - name: PORT
              value: "8889"
          ports:
            - containerPort: 8889
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hexa-demo-config
  name: hexa-demo-config
  namespace: hexa-demo
spec:
  type: NodePort
  ports:
    - port: 8889
      targetPort: 8889
  selector:
    app: hexa-demo-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hexa-demo-opa-server-agent-config
  namespace: hexa-demo
data:
  config.yaml: |
    services:
      - name: test
        url: http://hexa-demo-config.hexa-demo.svc.cluster.local:8889
    bundles:
      authz:
        service: test
        resource: bundles/bundle.tar.gz
        persist: true
        polling:
          min_delay_seconds: 4
          max_delay_seconds: 12
    decision_logs:
      console: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexa-demo-opa-server-agent
  namespace: hexa-demo
spec:
  selector:
    matchLabels:
      app: hexa-demo-opa-server-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: hexa-demo-opa-server-agent
    spec:
      volumes:
        - name: hexa-demo-opa-server-agent-config
          configMap:
            name: hexa-demo-opa-server-agent-config
      containers:
        - name: hexa-demo-opa-server-agent
          image: openpolicyagent/opa:latest
          volumeMounts:
            - readOnly: true
              mountPath: /config
              name: hexa-demo-opa-server-agent-config
          args:
            - "run"
            - "--server"
            - "--addr"
            - "0.0.0.0:8887"
            - "--config-file"
            - "/config/config.yaml"
          env:
            - name: PORT
              value: "8887"
          ports:
            - containerPort: 8887
---
apiVersion: v1
kind: Service
metadata:
  name: hexa-demo-opa-server-agent
  namespace: hexa-demo
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "config-default-opa-server"}'
  labels:
    app: hexa-demo-opa-server-agent
spec:
  type: NodePort
  ports:
    - port: 8887
      targetPort: 8887
  selector:
    app: hexa-demo-opa-server-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hexa-demo
  name: hexa-demo
  namespace: hexa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexa-demo
  template:
    metadata:
      labels:
        app: hexa-demo
    spec:
      containers:
        - image: ${IMAGE}
          name: hexa-demo
          imagePullPolicy: Always
          command:
            - demo
          env:
            - name: PORT
              value: "8886"
            - name: OPA_SERVER_URL
              value: http://hexa-demo-opa-server-agent.hexa-demo.svc.cluster.local:8887/v1/data/authz/allow
          ports:
            - containerPort: 8886
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  labels:
    app: hexa-demo
  name: hexa-demo
  namespace: hexa-demo
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: hexa-demo-secret
  healthCheck:
    checkIntervalSec: 15
    port: 8886
    type: HTTP
    requestPath: /health
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hexa-demo
  name: hexa-demo
  namespace: hexa-demo
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "hexa-demo"}'
spec:
  ports:
    - port: 8886
      protocol: TCP
      targetPort: 8886
  selector:
    app: hexa-demo
  type: NodePort
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: hexa-demo-certificate
  namespace: hexa-demo
  labels:
    app: hexa-demo
spec:
  domains:
    - hexa-demo.${DOMAIN}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hexa-demo
  namespace: hexa-demo
  labels:
    app: hexa-demo
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "hexa-demo-static-ip"
    networking.gke.io/managed-certificates: "hexa-demo-certificate"
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: hexa-demo
      port:
        number: 8886